-- [시퀀스 생성 코드 파일]

--○1. 호스트 회원정보 시퀀스 생성
CREATE SEQUENCE HOST_SEQ
MAXVALUE 9999
NOCACHE;

--○2. 관리자 정보 시퀀스 생성
CREATE SEQUENCE ADMIN_SEQ
MAXVALUE 9999
NOCACHE;

--○17. 게스트 회원 정보 시퀀스 생성
CREATE SEQUENCE GUEST_SEQ
MAXVALUE 9999
NOCACHE;

--○18. 지역 중분류 범례 테이블 생성
CREATE SEQUENCE LOCATION_SEQ
MAXVALUE 9999
NOCACHE;

--○19. 스터디카페 정보 시퀀스 생성
CREATE SEQUENCE STUDYCAFE_SEQ
MAXVALUE 9999
NOCACHE;

--○21. 호스트 개인정보 테이블 생성
CREATE SEQUENCE HOST_INFO_SEQ
MAXVALUE 9999
NOCACHE;

--○22. 호스트 회원 탈퇴 테이블 생성
CREATE SEQUENCE HOST_UNREG_SEQ
MAXVALUE 9999
NOCACHE;

--○23. 공지사항 테이블 생성
CREATE SEQUENCE NOTICE_SEQ
MAXVALUE 9999
NOCACHE;

--○25. 이웃 관리 테이블 생성
CREATE SEQUENCE FRIEND_MANAGE_SEQ
MAXVALUE 9999
NOCACHE;

--○26. 그룹 개설 요청 테이블 생성
CREATE SEQUENCE GROUP_REGISTRATION_SEQ
MAXVALUE 9999
NOCACHE;

--○27. 스터디룸 정보 테이블 생성
CREATE SEQUENCE STUDYROOM_SEQ
MAXVALUE 9999
NOCACHE;

--○28. 게시글 테이블 생성
CREATE SEQUENCE BOARD_SEQ
MAXVALUE 9999
NOCACHE;

--○29. 개인 일정 테이블 생성
CREATE SEQUENCE SCHEDULE_SEQ
MAXVALUE 9999
NOCACHE;

--○30. 스터디카페 즐겨찾기 테이블 생성
CREATE SEQUENCE BOOKMARK_SEQ
MAXVALUE 9999
NOCACHE;

--○31. 게스트 개인정보 테이블 생성
CREATE SEQUENCE GUEST_INFO_SEQ
MAXVALUE 9999
NOCACHE;

--○32. 게스트 회원 탈퇴 테이블 생성
CREATE SEQUENCE GUEST_UNREG_SEQ
MAXVALUE 9999
NOCACHE;

--○33. 비공개 스터디그룹 비밀번호 테이블 생성
CREATE SEQUENCE GROUP_PW_SEQ
MAXVALUE 9999
NOCACHE;

--○34. 스터디그룹 가입 요청 테이블
CREATE SEQUENCE GROUP_JOIN_SEQ
MAXVALUE 9999
NOCACHE;

--○35. 스터디룸 예약 테이블 생성
CREATE SEQUENCE RESERVATION_SEQ
MAXVALUE 9999
NOCACHE;

--○36. 게시글 스크랩 테이블 생성
CREATE SEQUENCE SCRAP_SEQ
MAXVALUE 9999
NOCACHE;

--○37. 댓글 테이블 생성
CREATE SEQUENCE REPLY_SEQ
MAXVALUE 9999
NOCACHE;

--○38. 게시판 신고 요청 테이블
CREATE SEQUENCE BOARD_RED_SEQ
MAXVALUE 9999
NOCACHE;

--○39. 그룹 추가 모집 테이블 생성
CREATE SEQUENCE GROUP_ADD_SEQ
MAXVALUE 9999
NOCACHE;

--○40. 스터디그룹 개설 요청 처리 테이블 생성
CREATE SEQUENCE GROUP_CONFIRM_SEQ
MAXVALUE 9999
NOCACHE;

--○41. 스터디그룹 모집 기간 종료 전 철회 테이블 생성
CREATE SEQUENCE GROUP_UNREGISTRATION_SEQ
MAXVALUE 9999
NOCACHE;

--○42. 스터디그룹 탈퇴 테이블 생성
CREATE SEQUENCE GROUP_UNREG_SEQ
MAXVALUE 9999
NOCACHE;

--○43. 스터디그룹 해체 테이블 생성
CREATE SEQUENCE BREAK_SEQ
MAXVALUE 9999
NOCACHE;

--○44. 게시글 신고 처리 결과 테이블 생성
CREATE SEQUENCE BOARD_REDDONE_SEQ
MAXVALUE 9999
NOCACHE;

--○45. 게시판 대댓글 테이블 생성
CREATE SEQUENCE RE_REPLY_SEQ
MAXVALUE 9999
NOCACHE;

--○46. 그룹 일정 테이블 생성
CREATE SEQUENCE GROUP_SCHEDULE_SEQ
MAXVALUE 9999
NOCACHE;

--○47. 그룹 게시글 테이블 생성
CREATE SEQUENCE GROUP_BOARD_SEQ
MAXVALUE 9999
NOCACHE;

--○48. 댓글 신고요청 테이블 생성
CREATE SEQUENCE REPLY_RED_SEQ
MAXVALUE 9999
NOCACHE;

--○49. 휴공 티켓 사용 내역 테이블 생성
CREATE SEQUENCE REST_TICKET_SEQ
MAXVALUE 9999
NOCACHE;

--○50. 스터디룸 예약 취소 내역 테이블 생성
CREATE SEQUENCE RECANCEL_SEQ
MAXVALUE 9999
NOCACHE;

--○51. 스터디룸 이용내역 피드백 테이블 생성
CREATE SEQUENCE FEEDBACK_SEQ
MAXVALUE 9999
NOCACHE;

--○52. 그룹장 변경 테이블 생성
CREATE SEQUENCE LEADER_CHANGE_SEQ
MAXVALUE 9999
NOCACHE;

--○53. 그룹 해체 패널티 테이블 생성
CREATE SEQUENCE PENALTY_BREAK_SEQ
MAXVALUE 9999
NOCACHE;

--○54. 대댓글 신고요청 테이블 생성
CREATE SEQUENCE REREPLY_RED_SEQ
MAXVALUE 9999
NOCACHE;

--○55. 댓글 신고처리 결과 테이블 생성
CREATE SEQUENCE REPLY_REDDONE_SEQ
MAXVALUE 9999
NOCACHE;

--○56. 그룹 게시글 스크랩 테이블 생성
CREATE SEQUENCE GROUP_SCRAP_SEQ
MAXVALUE 9999
NOCACHE;

--○57. 호스트 신고 요청 테이블 생성
CREATE SEQUENCE HOST_RED_SEQ
MAXVALUE 9999
NOCACHE;

--○58. 게시글 개인 패널티 테이블 생성
CREATE SEQUENCE PENALTY_BOARD_SEQ
MAXVALUE 9999
NOCACHE;

--○59. 그룹 게시판 댓글 테이블 생성
CREATE SEQUENCE GROUP_REPLY_SEQ
MAXVALUE 9999
NOCACHE;

--○60. 그룹 게시글 신고 요청 테이블 생성
CREATE SEQUENCE GROUP_BOARDRED_SEQ
MAXVALUE 9999
NOCACHE;

--○61. 스터디카페 리뷰 테이블 생성
CREATE SEQUENCE REVIEW_SEQ
MAXVALUE 9999
NOCACHE;

--○62. 참석자 명단 내역 테이블 생성
CREATE SEQUENCE ATTENDANCE_LIST_SEQ
MAXVALUE 9999
NOCACHE;

--○63. 스터디그룹 모임 내역 테이블 생성
CREATE SEQUENCE GROUP_MEETLIST_SEQ
MAXVALUE 9999
NOCACHE;

--○64. 대댓글 신고처리 결과 테이블 생성
CREATE SEQUENCE REREPLY_REDDONE_SEQ
MAXVALUE 9999
NOCACHE;

--○65. 호스트 신고처리 결과 테이블 생성
CREATE SEQUENCE HOST_REDDONE_SEQ
MAXVALUE 9999
NOCACHE;

--○66. 댓글 개인 패널티 테이블 생성
CREATE SEQUENCE PENALTY_REPLY_SEQ
MAXVALUE 9999
NOCACHE;

--○67. 그룹 게시판 댓글 신고요청 테이블 생성
CREATE SEQUENCE GROUP_REPLYRED_SEQ
MAXVALUE 9999
NOCACHE;

--○68. 그룹 게시글 신고 처리결과 테이블 생성
CREATE SEQUENCE GROUP_BOARDREDDONE_SEQ
MAXVALUE 9999
NOCACHE;

--○69. 불참 테이블 생성
CREATE SEQUENCE UNATTENDANCE_SEQ
MAXVALUE 9999
NOCACHE;

--○70. 그룹 패널티 테이블 생성
CREATE SEQUENCE PENALTY_GROUP_SEQ
MAXVALUE 9999
NOCACHE;

--○71. 그룹 내 댓글 신고처리결과 테이블 생성
CREATE SEQUENCE GROUP_REPLYREDDONE_SEQ
MAXVALUE 9999
NOCACHE;

--○72. 그룹 내 게시글 개인 패널티 테이블 생성
CREATE SEQUENCE PENALTY_GROUPBOARD_SEQ
MAXVALUE 9999
NOCACHE;

--○73. 불참 패널티 테이블 생성
CREATE SEQUENCE PENALTY_UNATTENDANCE_SEQ
MAXVALUE 9999
NOCACHE;

--○74. 그룹 내 댓글 개인패널티 테이블 생성
CREATE SEQUENCE PENALTY_GROUPREPLY_SEQ
MAXVALUE 9999
NOCACHE;

--○75. 그룹 내 대댓글 개인패널티 테이블 생성
CREATE SEQUENCE PENALTY_REREPLY_SEQ
MAXVALUE 9999
NOCACHE;



--○76. 스터디카페 비활성화 테이블 생성
CREATE SEQUENCE CAFEUNREG_SEQ
MAXVALUE 9999
NOCACHE;


--○77. 스터디룸 비활성화 테이블 생성
CREATE SEQUENCE ROOMUNREG_SEQ
MAXVALUE 9999
NOCACHE;


