--[ COMMTENT 생성 코드 ]


-- GUEST 코멘트
COMMENT ON TABLE GUEST IS '게스트회원정보';
COMMENT ON COLUMN GUEST.GU_CODE IS '게스트코드';
COMMENT ON COLUMN GUEST.GU_ID IS '게스트아이디';
COMMENT ON COLUMN GUEST.GU_PW IS '게스트비밀번호';
COMMENT ON COLUMN GUEST.GU_NICK IS '게스트닉네임';
COMMENT ON COLUMN GUEST.GU_DATE IS '게스트가입일자';
COMMENT ON COLUMN GUEST.CATEGORY_CODE IS '카테고리코드';

-- HOST 코멘트
COMMENT ON TABLE HOST IS '호스트회원정보';
COMMENT ON COLUMN HOST.HO_CODE IS '호스트코드';
COMMENT ON COLUMN HOST.HO_ID IS '호스트아이디';
COMMENT ON COLUMN HOST.HO_PW IS '호스트비밀번호';
COMMENT ON COLUMN HOST.HO_DATE IS '호스트가입일자';

-- ADMIN 코멘트
COMMENT ON TABLE ADMIN IS '관리자회원정보';
COMMENT ON COLUMN ADMIN.AD_CODE IS '관리자코드';
COMMENT ON COLUMN ADMIN.AD_NICK IS '관리자닉네임';
COMMENT ON COLUMN ADMIN.AD_PW IS '관리자비밀번호';
COMMENT ON COLUMN ADMIN.AD_DATE IS '관리자등록일자';

-- FRIEND_MANAGE 코멘트
COMMENT ON TABLE FRIEND_MANAGE IS '이웃관리';
COMMENT ON COLUMN FRIEND_MANAGE.FM_CODE IS '이웃관리코드';
COMMENT ON COLUMN FRIEND_MANAGE.FM_DATE IS '이웃등록 일자';
COMMENT ON COLUMN FRIEND_MANAGE.GU_CODE IS '게스트코드';
COMMENT ON COLUMN FRIEND_MANAGE.GU_FMCODE IS '당한게스트코드';
COMMENT ON COLUMN FRIEND_MANAGE.FT_CODE IS '이웃유형코드';


-- GROUP_REGISTRATION 코멘트
COMMENT ON TABLE GROUP_REGISTRATION IS '스터디그룹개설요청=게시글등록';
COMMENT ON COLUMN GROUP_REGISTRATION.GR_CODE IS '스터디그룹개설요청코드';
COMMENT ON COLUMN GROUP_REGISTRATION.GR_DATE IS '개설요청일자';
COMMENT ON COLUMN GROUP_REGISTRATION.GR_NAME IS '그룹명';
COMMENT ON COLUMN GROUP_REGISTRATION.GR_COUNT IS '최대인원수';
COMMENT ON COLUMN GROUP_REGISTRATION.GR_SUBJECT IS '스터디주제';
COMMENT ON COLUMN GROUP_REGISTRATION.GR_COMMENT IS '한마디';
COMMENT ON COLUMN GROUP_REGISTRATION.GU_CODE IS '게스트코드';
COMMENT ON COLUMN GROUP_REGISTRATION.AGE_CODE IS '연령대코드';
COMMENT ON COLUMN GROUP_REGISTRATION.GENDER_CODE IS '성별코드';
COMMENT ON COLUMN GROUP_REGISTRATION.LS_CODE IS '지역중분류코드';
COMMENT ON COLUMN GROUP_REGISTRATION.CATEGORY_CODE IS '카테고리코드';
COMMENT ON COLUMN GROUP_REGISTRATION.GO_CODE IS '스터디그룹공개여부코드';


-- GENDER 코멘트
COMMENT ON TABLE GENDER IS '성별';
COMMENT ON COLUMN GENDER.GENDER_CODE IS '성별코드';
COMMENT ON COLUMN GENDER.GENDER_RANGE IS '성별';


-- GROUP_OPEN 코멘트
COMMENT ON TABLE GROUP_OPEN IS '스터디그룹공개여부';
COMMENT ON COLUMN GROUP_OPEN.GO_CODE IS '스터디그룹공개여부코드';
COMMENT ON COLUMN GROUP_OPEN.GO_CHECK IS '공개여부';


-- CATEGORY 코멘트
COMMENT ON TABLE CATEGORY IS '카테고리';
COMMENT ON COLUMN CATEGORY.CATEGORY_CODE IS '카테고리코드';
COMMENT ON COLUMN CATEGORY.CATEGORY_LIST IS '카테고리대분류';

-- GROUP_PW 코멘트
COMMENT ON TABLE GROUP_PW IS '스터디그룹비밀번호';
COMMENT ON COLUMN GROUP_PW.GP_CODE IS '스터디그룹비밀번호코드';
COMMENT ON COLUMN GROUP_PW.GP_PW IS '비밀번호';
COMMENT ON COLUMN GROUP_PW.GR_CODE IS '스터디그룹개설요청코드';

-- LOCATION_SECOND 코멘트
COMMENT ON TABLE LOCATION_SECOND IS '지역중분류';
COMMENT ON COLUMN LOCATION_SECOND.LS_CODE IS '지역중분류코드';
COMMENT ON COLUMN LOCATION_SECOND.LS_LIST IS '지역중분류';
COMMENT ON COLUMN LOCATION_SECOND.LF_CODE IS '지역대분류코드';

-- AGE 코멘트
COMMENT ON TABLE AGE IS '연령대';
COMMENT ON COLUMN AGE.AGE_CODE IS '연령대코드';
COMMENT ON COLUMN AGE.AGE_RANGE IS '연령대';

-- GROUP_JOIN 코멘트
COMMENT ON TABLE GROUP_JOIN IS '스터디그룹 가입요청';
COMMENT ON COLUMN GROUP_JOIN.GJ_CODE IS '스터디그룹가입요청코드';
COMMENT ON COLUMN GROUP_JOIN.GJ_DATE IS '가입요청일자';
COMMENT ON COLUMN GROUP_JOIN.GU_CODE IS '게스트코드';
COMMENT ON COLUMN GROUP_JOIN.GR_CODE IS '스터디그룹개설요청코드';


-- REASON 코멘트
COMMENT ON TABLE REASON IS '사유';
COMMENT ON COLUMN REASON.REASON_CODE IS '사유코드';
COMMENT ON COLUMN REASON.REASON IS '사유';

-- GROUP_UNREG 코멘트
COMMENT ON TABLE GROUP_UNREG IS '스터디그룹원탈퇴';
COMMENT ON COLUMN GROUP_UNREG.GUN_CODE IS '스터디그룹탈퇴코드';
COMMENT ON COLUMN GROUP_UNREG.GUN_DATE IS '탈퇴일자';
COMMENT ON COLUMN GROUP_UNREG.REASON_CODE IS '사유코드';
COMMENT ON COLUMN GROUP_UNREG.GJ_CODE IS '스터디그룹가입요청코드';

-- BREAK 코멘트
COMMENT ON TABLE BREAK IS '스터디그룹해체';
COMMENT ON COLUMN BREAK.BR_CODE IS '스터디그룹해체코드';
COMMENT ON COLUMN BREAK.BR_DATE IS '해체일자';
COMMENT ON COLUMN BREAK.REASON_CODE IS '사유코드';
COMMENT ON COLUMN BREAK.GC_CODE IS '개설요청 처리 코드';


-- PENALTY_GROUPREPLY 코멘트
COMMENT ON TABLE PENALTY_GROUPREPLY IS '그룹댓글 개인 패널티';
COMMENT ON COLUMN PENALTY_GROUPREPLY.PGR_CODE IS '그룹 내 개인 패널티 코드';
COMMENT ON COLUMN PENALTY_GROUPREPLY.PGR_DATE IS '패널티 부여 일자';
COMMENT ON COLUMN PENALTY_GROUPREPLY.GRRD_CODE IS '신고처리결과코드';


-- REDSTATE 코멘트
COMMENT ON TABLE REDSTATE IS '신고처리';
COMMENT ON COLUMN REDSTATE.RED_CODE IS '신고처리코드';
COMMENT ON COLUMN REDSTATE.REDSTATE IS '신고처리상태';

-- BOARD_REDDONE 코멘트
COMMENT ON TABLE BOARD_REDDONE IS '전체 게시글 신고처리결과';
COMMENT ON COLUMN BOARD_REDDONE.BRD_CODE IS '전체 게시글신고처리결과코드';
COMMENT ON COLUMN BOARD_REDDONE.BRD_DATE IS '처리날짜';
COMMENT ON COLUMN BOARD_REDDONE.RED_CODE IS '신고처리코드';
COMMENT ON COLUMN BOARD_REDDONE.BOR_CODE IS '신고요청코드';


-- STUDYCAFE 코멘트
COMMENT ON TABLE STUDYCAFE IS '스터디카페정보';
COMMENT ON COLUMN STUDYCAFE.SC_CODE IS '스터디카페코드';
COMMENT ON COLUMN STUDYCAFE.SC_NAME IS '스터디카페명';
COMMENT ON COLUMN STUDYCAFE.SC_ADDR1 IS '스터디카페주소';
COMMENT ON COLUMN STUDYCAFE.SC_ADDR2 IS '상세주소';
COMMENT ON COLUMN STUDYCAFE.SC_TEL IS '전화번호';
COMMENT ON COLUMN STUDYCAFE.SC_OPENHOUR IS '운영시작시간';
COMMENT ON COLUMN STUDYCAFE.SC_CLOSEHOUR IS '운영종료시간';
COMMENT ON COLUMN STUDYCAFE.SC_CONVENIENT IS '편의시설';
COMMENT ON COLUMN STUDYCAFE.SC_SURROUND IS '주변시설';
COMMENT ON COLUMN STUDYCAFE.SC_CAUTION IS '유의사항';
COMMENT ON COLUMN STUDYCAFE.SC_DETAIL IS '상세설명';
COMMENT ON COLUMN STUDYCAFE.SC_RESNUMBER IS '사업자 등록번호';
COMMENT ON COLUMN STUDYCAFE.SC_DATE IS '카페정보등록일자';
COMMENT ON COLUMN STUDYCAFE.SC_FILE IS '첨부파일';
COMMENT ON COLUMN STUDYCAFE.AD_PERDATE IS '관리자승인날짜';
COMMENT ON COLUMN STUDYCAFE.HO_CODE IS '호스트코드';
COMMENT ON COLUMN STUDYCAFE.AD_CODE IS '관리자코드';                
COMMENT ON COLUMN STUDYCAFE.AD_CHCODE IS '관리자확인상태코드';           -- 확인 / 미확인

-- STUDYROOM 코멘트
COMMENT ON TABLE STUDYROOM IS '스터디룸';
COMMENT ON COLUMN STUDYROOM.SR_CODE IS '스터디룸코드';
COMMENT ON COLUMN STUDYROOM.SR_NAME IS '스터디룸명';
COMMENT ON COLUMN STUDYROOM.SR_COUNT IS '최대 수용 인원';
COMMENT ON COLUMN STUDYROOM.SR_PRICE IS '가격';
COMMENT ON COLUMN STUDYROOM.SC_CODE IS '스터디카페코드';

-- RESERVATION 코멘트
COMMENT ON TABLE RESERVATION IS '스터디룸예약';
COMMENT ON COLUMN RESERVATION.RE_CODE IS '스터디룸 예약 코드';
COMMENT ON COLUMN RESERVATION.RE_STARTDATE IS '이용예정날짜';
COMMENT ON COLUMN RESERVATION.RE_STARTHOUR IS '이용시작시간';
COMMENT ON COLUMN RESERVATION.RE_ENDHOUR IS '이용종료시간';
COMMENT ON COLUMN RESERVATION.RE_COUNT IS '인원';
COMMENT ON COLUMN RESERVATION.RE_DATE IS '예약요청날짜';
COMMENT ON COLUMN RESERVATION.GJ_CODE IS '스터디그룹가입요청코드';
COMMENT ON COLUMN RESERVATION.SR_CODE IS '스터디룸코드';


-- PENALTY_BREAK 코멘트
COMMENT ON TABLE PENALTY_BREAK IS '그룹강제종료 시 개인 패널티';
COMMENT ON COLUMN PENALTY_BREAK.PB_CODE IS '개인 패널티 코드';
COMMENT ON COLUMN PENALTY_BREAK.BR_CODE IS '스터디그룹해체코드';
COMMENT ON COLUMN PENALTY_BREAK.GJ_CODE IS '스터디그룹가입요청코드';


-- BOARD_FIRST 코멘트
COMMENT ON TABLE BOARD_FIRST IS '게시판 대분류';
COMMENT ON COLUMN BOARD_FIRST.BF_CODE IS '대분류 코드';
COMMENT ON COLUMN BOARD_FIRST.BF_LIST IS '대분류 항목';

-- BOARD_SECOND 코멘트
COMMENT ON TABLE BOARD_SECOND IS '게시판 소분류';
COMMENT ON COLUMN BOARD_SECOND.BS_CODE IS '소분류 코드';
COMMENT ON COLUMN BOARD_SECOND.BS_LIST IS '소분류 항목';
COMMENT ON COLUMN BOARD_SECOND.BF_CODE IS '대분류 코드';

-- BOARD 코멘트
COMMENT ON TABLE BOARD IS '전체게시글';
COMMENT ON COLUMN BOARD.BO_CODE IS '게시글 코드';
COMMENT ON COLUMN BOARD.BO_DATE IS '작성일자';
COMMENT ON COLUMN BOARD.BO_TITLE IS '제목';
COMMENT ON COLUMN BOARD.BO_CONTENT IS '내용';
COMMENT ON COLUMN BOARD.BO_VIEW IS '조회수';
COMMENT ON COLUMN BOARD.BO_MODATE IS '최종수정날짜';
COMMENT ON COLUMN BOARD.BO_FILE IS '첨부파일';
COMMENT ON COLUMN BOARD.BS_CODE IS '소분류 코드';
COMMENT ON COLUMN BOARD.GU_CODE IS '게스트코드';

-- SCRAP 코멘트
COMMENT ON TABLE SCRAP IS '스크랩';
COMMENT ON COLUMN SCRAP.SCRAP_CODE IS '스크랩 코드';
COMMENT ON COLUMN SCRAP.SCRAP_DATE IS '스크랩 날짜';
COMMENT ON COLUMN SCRAP.BO_CODE IS '게시글 코드';
COMMENT ON COLUMN SCRAP.GU_CODE IS '게스트코드';

-- REPLY 코멘트
COMMENT ON TABLE REPLY IS '전체댓글';
COMMENT ON COLUMN REPLY.RP_CODE IS '댓글코드';
COMMENT ON COLUMN REPLY.RP_DATE IS '작성날짜';
COMMENT ON COLUMN REPLY.RP_CONTENT IS '댓글내용';
COMMENT ON COLUMN REPLY.RP_MODATE IS '최종수정날짜';
COMMENT ON COLUMN REPLY.GU_CODE IS '게스트코드';
COMMENT ON COLUMN REPLY.BO_CODE IS '게시글 코드';

-- RE_REPLY 코멘트
COMMENT ON TABLE RE_REPLY IS '전체대댓글';
COMMENT ON COLUMN RE_REPLY.RRE_CODE IS '대댓글 코드';
COMMENT ON COLUMN RE_REPLY.RRE_CONTENT IS '대댓글 내용';
COMMENT ON COLUMN RE_REPLY.RRE_DATE IS '대댓글 날짜';
COMMENT ON COLUMN RE_REPLY.RRE_MODATE IS '최종수정날짜';
COMMENT ON COLUMN RE_REPLY.RP_CODE IS '댓글코드';
COMMENT ON COLUMN RE_REPLY.GU_CODE IS '게스트코드';


-- GROUP_SCHEDULE 코멘트
COMMENT ON TABLE GROUP_SCHEDULE IS '그룹 일정';
COMMENT ON COLUMN GROUP_SCHEDULE.GSCH_CODE IS '그룹 일정 코드';
COMMENT ON COLUMN GROUP_SCHEDULE.GSCH_DATE IS '일정 날짜';
COMMENT ON COLUMN GROUP_SCHEDULE.GSCH_NAME IS '일정 명';
COMMENT ON COLUMN GROUP_SCHEDULE.GSCH_CONTENT IS '일정 내용';
COMMENT ON COLUMN GROUP_SCHEDULE.GSCH_LOCATION IS '장소';
COMMENT ON COLUMN GROUP_SCHEDULE.GSCH_STARTHOUR IS '일정시작시간';
COMMENT ON COLUMN GROUP_SCHEDULE.GSCH_ENDHOUR IS '일정종료시간';
COMMENT ON COLUMN GROUP_SCHEDULE.GSCH_REGDATE IS '일정 등록일자';
COMMENT ON COLUMN GROUP_SCHEDULE.GSCH_MODATE IS '일정 최종 수정 날짜';
COMMENT ON COLUMN GROUP_SCHEDULE.GJ_CODE IS '스터디그룹가입요청코드';
COMMENT ON COLUMN GROUP_SCHEDULE.ATT_CODE IS '일정 참석자 유무 코드';


-- SCHEDULE 코멘트
COMMENT ON TABLE SCHEDULE IS '개인일정';
COMMENT ON COLUMN SCHEDULE.SCH_CODE IS '개인 일정 코드';
COMMENT ON COLUMN SCHEDULE.SCH_DATE IS '일정 날짜';
COMMENT ON COLUMN SCHEDULE.SCH_NAME IS '일정 명';
COMMENT ON COLUMN SCHEDULE.SCH_CONTENT IS '일정 내용';
COMMENT ON COLUMN SCHEDULE.SCH_REGDATE IS '일정 등록 일자';
COMMENT ON COLUMN SCHEDULE.GU_CODE IS '게스트코드';

-- BOOKMARK 코멘트
COMMENT ON TABLE BOOKMARK IS '즐겨찾기';
COMMENT ON COLUMN BOOKMARK.BM_CODE IS '즐겨찾기 코드';
COMMENT ON COLUMN BOOKMARK.BM_DATE IS '등록일자';
COMMENT ON COLUMN BOOKMARK.SC_CODE IS '스터디카페코드';
COMMENT ON COLUMN BOOKMARK.GU_CODE IS '게스트코드';

-- PERIOD 코멘트
COMMENT ON TABLE PERIOD IS '그룹모집기간분류';
COMMENT ON COLUMN PERIOD.PERIOD_CODE IS '모집기간분류코드';
COMMENT ON COLUMN PERIOD.PERIOD_STATE IS '모집분류';

-- GUEST_INFO 코멘트
COMMENT ON TABLE GUEST_INFO IS '게스트개인정보';
COMMENT ON COLUMN GUEST_INFO.GU_NAME IS '게스트이름';
COMMENT ON COLUMN GUEST_INFO.GU_TEL IS '게스트전화번호';
COMMENT ON COLUMN GUEST_INFO.GU_SSN IS '게스트주민번호';
COMMENT ON COLUMN GUEST_INFO.GU_EMAIL IS '게스트메일';
COMMENT ON COLUMN GUEST_INFO.GU_CODE IS '게스트코드';


-- GUEST_UNREG 코멘트
COMMENT ON TABLE GUEST_UNREG IS '게스트회원탈퇴';
COMMENT ON COLUMN GUEST_UNREG.GU_UNCODE IS '게스트회원탈퇴코드';
COMMENT ON COLUMN GUEST_UNREG.GU_UNDATE IS '회원탈퇴일자';
COMMENT ON COLUMN GUEST_UNREG.GU_CODE IS '게스트코드';
COMMENT ON COLUMN GUEST_UNREG.REASON_CODE IS '사유코드';



COMMENT ON TABLE HOST_INFO IS '호스트 개인정보 테이블';

COMMENT ON COLUMN HOST_INFO.HO_NAME IS '호스트이름';
COMMENT ON COLUMN HOST_INFO.HO_TEL IS '호스트전화번호';
COMMENT ON COLUMN HOST_INFO.HO_SSN IS '호스트주민번호';
COMMENT ON COLUMN HOST_INFO.HO_EMAIL IS '호스트이메일';
COMMENT ON COLUMN HOST_INFO.HO_CODE IS '호스트코드';

COMMENT ON TABLE FRIEND_TYPE IS '이웃 유형 테이블';

COMMENT ON COLUMN FRIEND_TYPE.FT_CODE IS '이웃유형 코드';
COMMENT ON COLUMN FRIEND_TYPE.FT_STATE IS '이웃 유형 차단/찜';

COMMENT ON TABLE HOST_UNREG IS '호스트 탈퇴 테이블';

COMMENT ON COLUMN HOST_UNREG.HO_UNCODE IS '호스트 탈퇴 코드';
COMMENT ON COLUMN HOST_UNREG.HO_UNDATE IS '호스트 탈퇴 날짜';
COMMENT ON COLUMN HOST_UNREG.HO_CODE IS '호스트 탈퇴 코드';
COMMENT ON COLUMN HOST_UNREG.REASON_CODE IS '사유';

COMMENT ON TABLE GROUP_BOARD IS '그룹 게시판 테이블';

COMMENT ON COLUMN GROUP_BOARD.GB_CODE IS '그룹게시글 코드';
COMMENT ON COLUMN GROUP_BOARD.GB_DATE IS '작성일자';
COMMENT ON COLUMN GROUP_BOARD.GB_TITLE IS '제목';
COMMENT ON COLUMN GROUP_BOARD.GB_CONTENT IS '내용';
COMMENT ON COLUMN GROUP_BOARD.GB_VIEW IS '조회수';
COMMENT ON COLUMN GROUP_BOARD.GB_MODATE IS '최종수정날짜';
COMMENT ON COLUMN GROUP_BOARD.GB_FILE IS '첨부파일';
COMMENT ON COLUMN GROUP_BOARD.GJ_CODE IS '스터디그룹가입요청코드';

COMMENT ON TABLE REPLY_RED IS '전체 댓글 신고요청 테이블';

COMMENT ON COLUMN REPLY_RED.RR_CODE IS '신고요청코드';
COMMENT ON COLUMN REPLY_RED.RR_DATE IS '신고요청일자';
COMMENT ON COLUMN REPLY_RED.REASON_CODE IS '사유코드';
COMMENT ON COLUMN REPLY_RED.GU_CODE IS '게스트코드';
COMMENT ON COLUMN REPLY_RED.RP_CODE IS '댓글코드';

COMMENT ON TABLE REPLY_REDDONE IS '전체 댓글 신고처리 테이블';

COMMENT ON COLUMN REPLY_REDDONE.RRD_CODE IS '전체댓글신고처리결과코드';
COMMENT ON COLUMN REPLY_REDDONE.RRD_DATE IS '처리날짜';
COMMENT ON COLUMN REPLY_REDDONE.RED_CODE IS '신고처리코드';
COMMENT ON COLUMN REPLY_REDDONE.RR_CODE IS '신고요청코드';

COMMENT ON TABLE REREPLY_RED IS '전체 대댓글 신고요청 테이블';

COMMENT ON COLUMN REREPLY_RED.RER_CODE IS '신고요청코드';
COMMENT ON COLUMN REREPLY_RED.RER_DATE IS '신고요청일자';
COMMENT ON COLUMN REREPLY_RED.REASON_CODE IS '사유코드';
COMMENT ON COLUMN REREPLY_RED.GU_CODE IS '게스트코드';
COMMENT ON COLUMN REREPLY_RED.RRE_CODE IS '대댓글 코드';

COMMENT ON TABLE REREPLY_REDDONE IS '전체 대댓글 신고처리 테이블';

COMMENT ON COLUMN REREPLY_REDDONE.RERD_CODE IS '전체대댓글신고처리결과코드';
COMMENT ON COLUMN REREPLY_REDDONE.RERD_DATE IS '처리날짜';
COMMENT ON COLUMN REREPLY_REDDONE.RED_CODE IS '신고처리코드';
COMMENT ON COLUMN REREPLY_REDDONE.RER_CODE IS '신고요청코드';

COMMENT ON TABLE BOARD_RED IS '전체 게시판 신고요청 테이블';

COMMENT ON COLUMN BOARD_RED.BOR_CODE IS '신고요청코드';
COMMENT ON COLUMN BOARD_RED.BOR_DATE IS '신고요청일자';
COMMENT ON COLUMN BOARD_RED.REASON_CODE IS '사유코드';
COMMENT ON COLUMN BOARD_RED.GU_CODE IS '게스트코드';
COMMENT ON COLUMN BOARD_RED.BO_CODE IS '게시글코드';

COMMENT ON TABLE PENALTY_GROUP IS '그룹 패널티 테이블';

COMMENT ON COLUMN PENALTY_GROUP.PG_CODE IS '그룹 패널티 코드';
COMMENT ON COLUMN PENALTY_GROUP.PG_DATE IS '패널티 부여 일자';
COMMENT ON COLUMN PENALTY_GROUP.HRD_CODE IS '호스트신고처리결과코드';

COMMENT ON TABLE REST_TICKET IS '휴공티켓 테이블';

COMMENT ON COLUMN REST_TICKET.RT_CODE IS '휴공티켓 사용 코드';
COMMENT ON COLUMN REST_TICKET.RT_DATE IS '사용 일자';
COMMENT ON COLUMN REST_TICKET.GJ_CODE IS '스터디그룹가입요청코드';
    
COMMENT ON TABLE RECANCEL IS '스터디카페 예약취소 테이블';

COMMENT ON COLUMN RECANCEL.RC_CODE IS '스터디룸예약취소내역코드';
COMMENT ON COLUMN RECANCEL.RC_DATE IS '예약 취소 날짜';
COMMENT ON COLUMN RECANCEL.RE_CODE IS '스터디룸 예약 코드';

COMMENT ON TABLE LOCATION_FIRST IS '지역 대분류 테이블';

COMMENT ON COLUMN LOCATION_FIRST.LF_CODE IS '지역대분류코드';
COMMENT ON COLUMN LOCATION_FIRST.LF_LIST IS '지역대분류';

COMMENT ON TABLE GROUP_SCRAP IS '그룹 스크랩 테이블';

COMMENT ON COLUMN GROUP_SCRAP.GBS_CODE IS '그룹스크랩 코드';
COMMENT ON COLUMN GROUP_SCRAP.GBS_DATE IS '스크랩 날짜';
COMMENT ON COLUMN GROUP_SCRAP.GB_CODE IS '그룹게시글 코드';
COMMENT ON COLUMN GROUP_SCRAP.GJ_CODE IS '스터디그룹가입요청코드';

COMMENT ON TABLE HOST_RED IS '호스트 신고요청 테이블';

COMMENT ON COLUMN HOST_RED.HR_CODE IS '호스트신고요청코드';
COMMENT ON COLUMN HOST_RED.HR_DATE IS '신고요청날짜';
COMMENT ON COLUMN HOST_RED.HR_FILE IS '첨부파일';
COMMENT ON COLUMN HOST_RED.FB_CODE IS '이용 피드백 내역 코드';
COMMENT ON COLUMN HOST_RED.REASON_CODE IS '사유코드';

COMMENT ON TABLE HOST_REDDONE IS '호스트 신고처리 테이블';

COMMENT ON COLUMN HOST_REDDONE.HRD_CODE IS '호스트신고처리결과코드';
COMMENT ON COLUMN HOST_REDDONE.HRD_DATE IS '신고처리날짜';
COMMENT ON COLUMN HOST_REDDONE.HR_CODE IS '호스트신고요청코드';
COMMENT ON COLUMN HOST_REDDONE.RED_CODE IS '신고처리코드';
    
COMMENT ON TABLE PENALTY_BOARD IS '게시물 개인 패널티 테이블';

COMMENT ON COLUMN PENALTY_BOARD.PBO_CODE IS '게시물개인 패널티 코드';
COMMENT ON COLUMN PENALTY_BOARD.PBO_DATE IS '패널티 부여 일자';
COMMENT ON COLUMN PENALTY_BOARD.BRD_CODE IS '전체 게시글신고처리결과코드';
 
COMMENT ON TABLE PENALTY_REPLY IS '전체댓글 패널티 테이블';

COMMENT ON COLUMN PENALTY_REPLY.PR_CODE IS '전체댓글 개인패널티 코드';
COMMENT ON COLUMN PENALTY_REPLY.PR_DATE IS '패널티 부여 일자';
COMMENT ON COLUMN PENALTY_REPLY.RRD_CODE IS '전체댓글신고처리결과코드';
    
COMMENT ON TABLE PENALTY_REREPLY IS '전체 대댓글 패널티 테이블';

COMMENT ON COLUMN PENALTY_REREPLY.PRR_CODE IS '대댓글개인 패널티 코드';
COMMENT ON COLUMN PENALTY_REREPLY.PRR_DATE IS '패널티 부여 일자';
COMMENT ON COLUMN PENALTY_REREPLY.RERD_CODE IS '전체대댓글신고처리결과코드';
        
COMMENT ON TABLE GROUP_REPLY IS '그룹 댓글 테이블';

COMMENT ON COLUMN GROUP_REPLY.GRE_CODE IS '그룹댓글코드';
COMMENT ON COLUMN GROUP_REPLY.GRE_DATE IS '작성날짜';
COMMENT ON COLUMN GROUP_REPLY.GRE_CONTENT IS '댓글내용';
COMMENT ON COLUMN GROUP_REPLY.GRE_MODATE IS '최종수정날짜';
COMMENT ON COLUMN GROUP_REPLY.GB_CODE IS '그룹게시글 코드';
COMMENT ON COLUMN GROUP_REPLY.GJ_CODE IS '스터디그룹가입요청코드';
                
COMMENT ON TABLE GROUP_REPLYRED IS '그룹 댓글 신고요청 테이블';

COMMENT ON COLUMN GROUP_REPLYRED.GRR_CODE IS '신고요청코드';
COMMENT ON COLUMN GROUP_REPLYRED.GRR_DATE IS '신고요청일자';
COMMENT ON COLUMN GROUP_REPLYRED.REASON_CODE IS '사유코드';
COMMENT ON COLUMN GROUP_REPLYRED.GRE_CODE IS '그룹댓글코드';
COMMENT ON COLUMN GROUP_REPLYRED.GJ_CODE IS '스터디그룹가입요청코드';
    
COMMENT ON TABLE GROUP_BOARDRED IS '그룹 게시글 신고요청 테이블';

COMMENT ON COLUMN GROUP_BOARDRED.GBR_CODE IS '그룹게시글신고요청코드';
COMMENT ON COLUMN GROUP_BOARDRED.GBR_DATE IS '신고요청일자';
COMMENT ON COLUMN GROUP_BOARDRED.REASON_CODE IS '사유코드';
COMMENT ON COLUMN GROUP_BOARDRED.GB_CODE IS '그룹댓글코드';
COMMENT ON COLUMN GROUP_BOARDRED.GJ_CODE IS '스터디그룹가입요청코드';    

COMMENT ON TABLE GROUP_REPLYREDDONE IS '그룹 댓글 신고처리 테이블';

COMMENT ON COLUMN GROUP_REPLYREDDONE.GRRD_CODE IS '신고처리결과코드';
COMMENT ON COLUMN GROUP_REPLYREDDONE.GRRD_DATE IS '처리날짜';
COMMENT ON COLUMN GROUP_REPLYREDDONE.RED_CODE IS '신고처리코드';
COMMENT ON COLUMN GROUP_REPLYREDDONE.GRR_CODE IS '신고요청코드';

  
COMMENT ON TABLE PENALTY_GROUPBOARD IS '그룹 내 개인 패널티 테이블';

COMMENT ON COLUMN PENALTY_GROUPBOARD.PGB_CODE IS '그룹 내 개인 패널티 코드';
COMMENT ON COLUMN PENALTY_GROUPBOARD.PGB_DATE IS '패널티 부여 일자';
COMMENT ON COLUMN PENALTY_GROUPBOARD.GBRD_CODE IS '그룹게시글신고처리결과코드';    


COMMENT ON TABLE REVIEW IS '스터디카페 후기 테이블';

COMMENT ON COLUMN REVIEW.RV_CODE IS '스터디카페리뷰코드';
COMMENT ON COLUMN REVIEW.RV_CONTENT IS '리뷰내용';
COMMENT ON COLUMN REVIEW.RV_DATE IS '작성일자'; 
COMMENT ON COLUMN REVIEW.RV_MODATE IS '최종수정날짜';
COMMENT ON COLUMN REVIEW.FB_CODE IS '이용 피드백 내역 코드';    

COMMENT ON TABLE NOTICE IS '공지사항 테이블';

COMMENT ON COLUMN NOTICE.NT_CODE IS '공지사항코드';
COMMENT ON COLUMN NOTICE.NT_TITLE IS '제목';
COMMENT ON COLUMN NOTICE.NT_CONTENT IS '내용'; 
COMMENT ON COLUMN NOTICE.NT_DATE IS '작성일자';
COMMENT ON COLUMN NOTICE.NT_VIEW IS '조회수'; 
COMMENT ON COLUMN NOTICE.NT_MODATE IS '최종수정날짜';
COMMENT ON COLUMN NOTICE.AD_CODE IS '관리자코드'; 
    
COMMENT ON TABLE ATTENDANCE_LIST IS '일정참석예정 리스트 테이블';

COMMENT ON COLUMN ATTENDANCE_LIST.ATTL_CODE IS '일정참석예정코드';
COMMENT ON COLUMN ATTENDANCE_LIST.GSCH_CODE IS '그룹 일정 코드';
COMMENT ON COLUMN ATTENDANCE_LIST.GJ_CODE IS '스터디그룹가입요청코드'; 

COMMENT ON TABLE ADMIN_STATE IS '관리자 상태 테이블';

COMMENT ON COLUMN ADMIN_STATE.AD_STATEDATE IS '비활성화 일자';
COMMENT ON COLUMN ADMIN_STATE.AD_CODE IS '관리자코드'; 

COMMENT ON TABLE GROUP_ADD IS '스터디그룹 추가모집요청 테이블';

COMMENT ON COLUMN GROUP_ADD.GA_CODE IS '스터디그룹추가모집요청코드';
COMMENT ON COLUMN GROUP_ADD.GA_DATE IS '추가모집요청일자';
COMMENT ON COLUMN GROUP_ADD.GR_CODE IS '스터디그룹개설요청코드';
COMMENT ON COLUMN GROUP_ADD.PERIOD_CODE IS '모집기간분류코드';

COMMENT ON TABLE PENALTY_UNATTENDANCE IS '불참패널티 테이블';

COMMENT ON COLUMN PENALTY_UNATTENDANCE.PU_CODE IS '불참패널티';
COMMENT ON COLUMN PENALTY_UNATTENDANCE.PU_DATE IS '패널티 부여일자';
COMMENT ON COLUMN PENALTY_UNATTENDANCE.UNATT_CODE IS '불참 코드';

COMMENT ON TABLE GROUP_MEETLIST IS '그룹 모임기록 리스트 테이블';

COMMENT ON COLUMN GROUP_MEETLIST.GM_CODE IS '그룹모임기록코드';
COMMENT ON COLUMN GROUP_MEETLIST.GM_CONTENT IS '모임 내용 기록';
COMMENT ON COLUMN GROUP_MEETLIST.GSCH_CODE IS '그룹 일정 코드';
    
COMMENT ON TABLE UNATTENDANCE IS '불참자 기록 테이블';

COMMENT ON COLUMN UNATTENDANCE.UNATT_CODE IS '불참 코드';
COMMENT ON COLUMN UNATTENDANCE.ATTL_CODE IS '일정참석예정코드';    

COMMENT ON TABLE FEEDBACK IS '스터디카페 이용 피드백 내역 테이블';

COMMENT ON COLUMN FEEDBACK.FB_CODE IS '이용 피드백 내역 코드';
COMMENT ON COLUMN FEEDBACK.FB_STATECODE IS '이용 피드백 판별 코드';
COMMENT ON COLUMN FEEDBACK.RE_CODE IS '스터디룸 예약 코드';    

COMMENT ON TABLE GROUP_CONFIRM IS '스터디카페 이용 피드백 내역 테이블';

COMMENT ON COLUMN GROUP_CONFIRM.GC_CODE IS '개설요청 처리 코드';
COMMENT ON COLUMN GROUP_CONFIRM.RS_CODE IS '모집 기간 종료 후 처리 상태 코드';
COMMENT ON COLUMN GROUP_CONFIRM.GR_CODE IS '스터디그룹개설요청코드';    
    
COMMENT ON TABLE REGISTRATION_STATE IS '모집기간 종료 후 처리상태 테이블';

COMMENT ON COLUMN REGISTRATION_STATE.RS_CODE IS '개설요청 처리 코드';
COMMENT ON COLUMN REGISTRATION_STATE.RS_STATE IS '모집 기간 종료 후 처리 상태 코드';    

COMMENT ON TABLE GROUP_UNREGISTRATION IS '모집기간 종료 전 철회 테이블';

COMMENT ON COLUMN GROUP_UNREGISTRATION.GUR_CODE IS '모집기간 종료 전 철회 코드';
COMMENT ON COLUMN GROUP_UNREGISTRATION.GUR_DATE IS '철회 요청 날짜';
COMMENT ON COLUMN GROUP_UNREGISTRATION.GR_CODE IS '스터디그룹개설요청코드';       
  
COMMENT ON TABLE GROUP_UNREGISTRATION IS '그룹장 변경 테이블';

COMMENT ON COLUMN LEADER_CHANGE.LC_CODE IS '그룹장 변경 코드';
COMMENT ON COLUMN LEADER_CHANGE.LC_DATE IS '처리 일자';
COMMENT ON COLUMN LEADER_CHANGE.GJ_CODE IS '스터디그룹가입요청코드';         
    
COMMENT ON TABLE FEEDBACK_STATE IS '스터디카페 이용 피드백 판별 테이블';

COMMENT ON COLUMN FEEDBACK_STATE.FB_STATECODE IS '이용 피드백 판별 코드';
COMMENT ON COLUMN FEEDBACK_STATE.FB_STATE IS '코드 내역';
    
COMMENT ON TABLE ADMIN_CHECK IS '관리자 확인 상태 테이블';

COMMENT ON COLUMN ADMIN_CHECK.AD_CHCODE IS '관리자확인상태코드';
COMMENT ON COLUMN ADMIN_CHECK.AD_CHECK IS '확인 상태';    
    
COMMENT ON TABLE ATTENDANCE IS '일정 참석자 유무 테이블';

COMMENT ON COLUMN ATTENDANCE.ATT_CODE IS '일정 참석자 유무 코드';
COMMENT ON COLUMN ATTENDANCE.ATT_STATE IS '참석자 유무';  


COMMENT ON TABLE CAFEUNREG IS '스터디카페 비활성화 테이블';

COMMENT ON COLUMN CAFEUNREG.CM_CODE IS '스터디카페 비활성화 코드';
COMMENT ON COLUMN CAFEUNREG.CM_DATE IS '스터디카페 비활성화 일자';  


COMMENT ON TABLE ROOMUNREG IS '스터디룸 비활성화 테이블';

COMMENT ON COLUMN ROOMUNREG.RM_CODE IS '스터디카페 비활성화 코드';
COMMENT ON COLUMN ROOMUNREG.RM_DATE IS '스터디카페 비활성화 일자';  


