-- [시퀀스 삭제 코드]

DROP SEQUENCE HOST_SEQ;

DROP SEQUENCE ADMIN_SEQ;

DROP SEQUENCE GUEST_SEQ;

DROP SEQUENCE LOCATION_SEQ;

DROP SEQUENCE STUDYCAFE_SEQ;

DROP SEQUENCE HOST_INFO_SEQ;

DROP SEQUENCE HOST_UNREG_SEQ;

DROP SEQUENCE NOTICE_SEQ;

DROP SEQUENCE FRIEND_MANAGE_SEQ;

DROP SEQUENCE GROUP_REGISTRATION_SEQ;

DROP SEQUENCE STUDYROOM_SEQ;

DROP SEQUENCE BOARD_SEQ;

DROP SEQUENCE SCHEDULE_SEQ;

DROP SEQUENCE BOOKMARK_SEQ;

DROP SEQUENCE GUEST_INFO_SEQ;

DROP SEQUENCE GUEST_UNREG_SEQ;

DROP SEQUENCE GROUP_PW_SEQ;

DROP SEQUENCE GROUP_JOIN_SEQ;

DROP SEQUENCE RESERVATION_SEQ;

DROP SEQUENCE SCRAP_SEQ;

DROP SEQUENCE REPLY_SEQ;

DROP SEQUENCE BOARD_RED_SEQ;

DROP SEQUENCE GROUP_ADD_SEQ;

DROP SEQUENCE GROUP_CONFIRM_SEQ;

DROP SEQUENCE GROUP_UNREGISTRATION_SEQ;

DROP SEQUENCE GROUP_UNREG_SEQ;

DROP SEQUENCE BREAK_SEQ;

DROP SEQUENCE BOARD_REDDONE_SEQ;

DROP SEQUENCE RE_REPLY_SEQ;

DROP SEQUENCE GROUP_SCHEDULE_SEQ;

DROP SEQUENCE GROUP_BOARD_SEQ;

DROP SEQUENCE REPLY_RED_SEQ;

DROP SEQUENCE REST_TICKET_SEQ;

DROP SEQUENCE RECANCEL_SEQ;

DROP SEQUENCE FEEDBACK_SEQ;

DROP SEQUENCE LEADER_CHANGE_SEQ;

DROP SEQUENCE PENALTY_BREAK_SEQ;

DROP SEQUENCE REREPLY_RED_SEQ;

DROP SEQUENCE REPLY_REDDONE_SEQ;

DROP SEQUENCE GROUP_SCRAP_SEQ;

DROP SEQUENCE HOST_RED_SEQ;

DROP SEQUENCE PENALTY_BOARD_SEQ;

DROP SEQUENCE GROUP_REPLY_SEQ;

DROP SEQUENCE GROUP_BOARDRED_SEQ;

DROP SEQUENCE REVIEW_SEQ;

DROP SEQUENCE ATTENDANCE_LIST_SEQ;

DROP SEQUENCE GROUP_MEETLIST_SEQ;

DROP SEQUENCE REREPLY_REDDONE_SEQ;

DROP SEQUENCE HOST_REDDONE_SEQ;

DROP SEQUENCE PENALTY_REPLY_SEQ;

DROP SEQUENCE GROUP_REPLYRED_SEQ;

DROP SEQUENCE GROUP_BOARDREDDONE_SEQ;

DROP SEQUENCE UNATTENDANCE_SEQ;

DROP SEQUENCE PENALTY_GROUP_SEQ;

DROP SEQUENCE GROUP_REPLYREDDONE_SEQ;

DROP SEQUENCE PENALTY_GROUPBOARD_SEQ;

DROP SEQUENCE PENALTY_UNATTENDANCE_SEQ;

DROP SEQUENCE PENALTY_GROUPREPLY_SEQ;

DROP SEQUENCE PENALTY_REREPLY_SEQ;

DROP SEQUENCE  CAFEUNREG_SEQ;

DROP SEQUENCE ROOMUNREG_SEQ;
